#NUMPY

Numpy-Numerical Python

Numpy is a Python library used for
working with arrays.

Python lists are a substitute for arrays,but they fail to deliver the Performance required while computing large sets of numerical data.

To address this issue we use the Numpy library of Python.Numpy offers an array object called ndarray

#NUMPY VS PYTHON LIST

Feature                | Python List                    | NumPy Array
-----------------------|--------------------------------|-------------------------------
Speed                  | Slow                           | Fast (optimized in C)
Data Types             | Mixed allowed                  | Same data type only
Memory Efficiency      | Less efficient                 | More efficient
Math Operations        | Manual loop                    | Direct (vectorized)
Built-in Functions     | Limited                        | Many powerful tools

Why is Numpy Faster than Lists?


Numpy arrays are stored at one continuous Place in memory unlike lists.so Processes can acceess and manipulate them very efficiently.









DATA TYPES IN NUMPY:

*Strings

*integer(32bit and 64bit)

*float(32bit and 64bit)

*boolean

*complex

What is a Numpy Array?

*Numpy array is a multidimensional data structure that is the core of scientific computing in python.

*All values in an array are homogeneous(of the same datatype)

*They provide efficient memory management,support various data types and are flexible with Indexing and slicing.



In [17]:
#CREATING AN ARRAY

import numpy as np    # alias -> np

arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [18]:
#type() -> This built-in Python functions tells us the type of the object Passed to it.

type(arr)


numpy.ndarray

In [19]:
#o create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [20]:
#get the data type of an array

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [21]:
#DIMENSTION IN ARRAYS

# ndim - To check the number of dimension of an array

#0D (zero-dimensional)	Scalar - A single element
#1D (one-dimensional)	Vector- A list of integers.
#2D (two-dimensional)	Matrix- A spreadsheet of data
#3D (three-dimensional)	Tensor- Storing a color image

import numpy as np

arr=np.array(42)
brr=np.array([1,2,3,4,5])
crr=np.array([[1,2,3],[4,5,6]])
drr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr.ndim)      # or print(np.ndim(a))
print(brr.ndim)
print(crr.ndim)
print(drr.ndim)



0
1
2
3


In [22]:
#forces minimum number of dimensions when creating an array
#f the data has fewer dimensions, NumPy will add extra dimensions (axes) in front.

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [23]:
#CREATING ARRAYS PYTHON VS NUMPY

l = []                     # create empty list
for i in range(10):
    l.append(i)
print(l)

np.arange(0,10)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#linspace - (start,stop,number of values btw them)

import numpy as np

arr=np.linspace(0,10,5)      #DEFAULT VALUES IN NUMPY IS FLOAT.
arr


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
#logspace - Logarithmic scale array(10 to the power) - (start,stop,noofvalues)

arr=np.logspace(1,3,3)
arr

array([  10.,  100., 1000.])

In [26]:
# zeros - Array full of zeros.
# ones - Array full of ones.

import numpy as np
arr1=np.zeros(5)             #() - no of values
print(arr1)

arr2=np.zeros([2,3])        # 2 rows and 3 columns
print(arr2)

arr3=np.ones([4,2],dtype=int)     #changing the datatype to int.
print(arr3)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [27]:
#full -> create an array full of any values. - (row,column),defaultvalue

arr=np.full(10,2)
print(arr)

arr2=np.full((2,3),5)
print(arr2)


[2 2 2 2 2 2 2 2 2 2]
[[5 5 5]
 [5 5 5]]


In [28]:
#empty - uninitialized array -> create an array without setting any values.

arr=np.empty([2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#random.rand -> random floats () -> no of elemets / size of a an array

arr=np.random.rand(5)
print(arr)

arr2=np.random.rand(2,5)
print(arr2)

[0.68243281 0.24745002 0.4153581  0.84811443 0.82508143]
[[0.03863125 0.37562494 0.95273377 0.90714032 0.87144283]
 [0.77698362 0.72083688 0.40537552 0.81356381 0.08932248]]


In [30]:
#random.randn -> random floats from standard normal distribution (mean(avg=0),std dev=1)
#prints both positive and negative value from 0 to 1

arr=np.random.randn(2,3)
print(arr)



[[ 1.19783659 -1.8201803   0.86776154]
 [-0.55243635 -0.14719707 -0.29615337]]


In [31]:
#np.random.randint -> just random integers - (from,to)

arr=np.random.randint(10,100)
arr

arr=np.random.randint(10,100,size=(2,3))
arr

array([[73, 79, 31],
       [76, 75, 96]])

In [32]:
#TYPECASTING -converting one data type into another

#converting list into numpy array.
import numpy as np
lst=["string",1,2,5.6]
arr=np.array(lst)
print(arr)

#converting int to float (vice versa also works)

arr=np.array([1,2,3,4],dtype=float)
print(arr)

#astype()
arr=np.array([1,2,3,4])
print(arr.dtype)

new_arr=arr.astype(float)
print(new_arr)

#Typecasting error

#arr = np.array(["hello", "world"])
#arr.astype(float)


['string' '1' '2' '5.6']
[1. 2. 3. 4.]
int64
[1. 2. 3. 4.]


In [33]:
#Shape - The shape of an array is the number of elements in each dimension.
#Numpy arrays have an attrib called shape that returns a tuple with each index having having the number of corresponding elements.

import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)


(2, 4)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [34]:
#Numpy Array Reshaping - changing the shape of an array
#shape of the array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change the number of elements in each dimension.

#Reshape from 1d to 2d

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr.reshape(4,3)
print(new_arr)

newarr=arr.reshape(2,3,2)
print(newarr)

#ry converting 1D array with 8 elements to a 2D array
# with 3 elements in each dimension (will raise an error):

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [35]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

#Note: We can not pass -1 to more than one dimension

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
#ravel -> convert 1D array returns the view

newarr=np.array([[1,2,3],[4,5,6]])
ravel=np.ravel(newarr)
print(ravel)

ravel[0]=100
print(ravel)
print(newarr)

[1 2 3 4 5 6]
[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


In [37]:
#Flattening the arrays

#Flattening array means converting a multidimensional array into a 1D array.
#returns a copy of the array.
#We can use reshape(-1) to do this.

import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
new_arr=arr.reshape(-1)
print(new_arr)

flat=arr.flatten()
print(flat)
flat[0]=1
print(flat)
print(arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [38]:
#Arithmetic opertors on Arrays

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)   # or print(np.add(a,b))
print(a-b)    # or print(np.subtract(a,b))
print(b-a)
print(a/b)
print(b//a)
print(a*b)     # or print(np.multiply(a,b))
print(a%b)     # or print(np.mod(a,b))
print(a**2)     # or print(np.power(a,b))

[5 7 9]
[-3 -3 -3]
[3 3 3]
[0.25 0.4  0.5 ]
[4 2 2]
[ 4 10 18]
[1 2 3]
[1 4 9]


In [39]:
#universal functions -> ufuncs

import numpy as np
arr=np.array([1,4,9,6])
print(np.sqrt(arr))
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

arr2 = np.array([0, np.pi, np.pi/2])
print(np.sin(arr2))
print(np.cos(arr2))



[1.         2.         3.         2.44948974]
[0.         1.38629436 2.19722458 1.79175947]
[0.         0.60205999 0.95424251 0.77815125]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 4.03428793e+02]
[0.0000000e+00 1.2246468e-16 1.0000000e+00]
[ 1.000000e+00 -1.000000e+00  6.123234e-17]


In [40]:
#Numpy Indexing - same as accessing an element an array (using index) starting starts with 0

import numpy as np

arr=np.array([1,2,3,4])
for i in range(0,4):
   print(arr[i])

print(arr[0])
print(arr[2]+arr[3])   #Numpy follows vectorisation

1
2
3
4
1
7


In [41]:
#Acess in 2D arrays

import numpy as np

arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[0,1])    #2nd element on 1st row
print(arr1[1,4])    #5th element on 2nd row
print(arr1[1,-1])       #Negative index starts from 1 (last element from 2nd dim)

2
10
10


In [42]:
#Acess in 3D arrays

import numpy as np

arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[0,1,2])
print(arr[0,2,1])

6
8


#Array Slicing

*Slicing in python means taking elements from one given index to another given index.

*we pass slice instead of index like this:[start:end]

*We can also define the step ,like this:[start,end,stop].

*If we dont pass start it is considered 0.

*If we dont pass end its considered length of array in that dimension.

*If we dont pass step its considered 1.





In [43]:
#Slicing in 1D arrays

import numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [44]:
#Slicing in 2D Arrays

import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])  # 0:2 means rows 0 and 1
print(arr[0:2,1:4])   #both rows columns 1 2 3
print(arr[::2])    #::2 means take every 2nd row, starting from index 0.

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
[[1 2 3 4 5]]


#Iterating Arrays

In [45]:
import numpy as np

#1D Array
arr=np.array([1,2,3])
for x in arr:
  print(x)

#2D Array
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)

#2D Array element wise
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
  for y in x:
    print(y)



1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [46]:
#Iterate 3D Arrays

arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in arr:
  print(x)

arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


In [47]:
#np.take -> built in function to perform indexing & slicing

arr=np.array([1,2,3,4,5,6])
print(np.take(arr,[0,2,4]))

array2=np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(array2,ind))

[1 3 5]
[10 30]


In [48]:
#nditer

arr=np.array([[1,2],[3,4]])
for x in np.nditer(arr):
  print(x)

1
2
3
4


In [49]:
#ndenumerate -> both index & values

for ind , x in np.ndenumerate(arr):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [50]:
#Transpose

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.transpose())   # or print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [51]:
#swapaxes -> swap 2 specific axes in a matrix

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.swapaxes(arr,0,1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


#Array Concatenation

*In sql we join tables based on a key , whereas in Numpy we join arrays by axes.


In [52]:
import numpy as np

#join two 1D array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr5=np.concatenate((arr1,arr2))
print(arr5)

#join two 2D Arrays (axis=1)
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6],[7,8]])
arr6=np.concatenate((arr3,arr4),axis=1)
print(arr6)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


Joining Arrays Using Stack Functions

*Stacking is same as concatenation,the only difference is that stacking is done along a new axes.

*we can concatenate two 1D arrays along the second axis which would result in putting them one over the other ie.Staking.

*We pass a sequence of arrays that we want to join to the stack() method along with the axis.If axis is not explicitly passes it is taken as 0.


*can be peformed by stack with axis or direclty use hstack or vstack

In [53]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2))
print(arr)

arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [54]:
#hstack -> horizontal stack

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

#vstack -> vertical stack
arr=np.vstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [55]:
#dstack() to stack along height, which is the same as depth.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


Array splitting

*splitting is reverse operation of joining.

*Joining merges multiple arrays into one and splitting breaks one array into multiple.

*we use array split() for splitting arrays we pass it the array we want to split and the number of splits.



In [56]:
import numpy as np

#1D Arrays
#split the array in  parts.
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

#split the array in 4 parts.
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)   #If the last elements than req , it will adjust from the end accordingly
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [57]:
#2D Arrays.

import numpy as np

arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [58]:
#Split the 2-D array into three 2-D arrays along columns

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [59]:
#An alternate solution is using hsplit() opposite of hstack()

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [60]:
#repeat - each element

arr=np.array([1,2,3])
print(np.repeat(arr,3))

#tile - repeat the whole array

print(np.tile(arr,2))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3]


In [61]:
import numpy as np

#where -> conditions
arr=np.array([1,2,3])
result=np.where(arr<2,"Low","High")
print(result)

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)         #prints the indexes.
print(x)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)          #Find the indexes where the values are odd:
print(x)

['Low' 'High' 'High']
(array([3, 5, 6]),)
(array([0, 2, 4, 6]),)


In [62]:
#The searchsorted() method is assumed to be used on sorted arrays.

import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)    #Find the indexes where the value 7 should be inserted:
print(x)

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)


arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

1
2
[1 2 3]


In [63]:
import numpy as np

#argwhere - row column positions(index) for 2d arrays

arr=np.array([10,25,35,50])
print(np.argwhere(arr>20))

[[1]
 [2]
 [3]]


In [64]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
total_sum=np.sum(arr)
print(total_sum)

column_sum=np.sum(arr,axis=0)
row_sum=np.sum(arr,axis=1)
print(column_sum)
print(row_sum)

21
[5 7 9]
[ 6 15]


In [65]:
import numpy as np

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

# Aggregation functions
print("1. Sum:", np.sum(arr))
print("2. Mean (Average):", np.mean(arr))
print("3. Median:", np.median(arr))
print("4. Standard Deviation:", np.std(arr))
print("5. Variance:", np.var(arr))
print("6. Minimum Value:", np.min(arr))
print("7. Maximum Value:", np.max(arr))
print("8. Index of Minimum Value:", np.argmin(arr))
print("9. Index of Maximum Value:", np.argmax(arr))
print("10. Cumulative Sum:", np.cumsum(arr))
print("11. Cumulative Product:", np.cumprod(arr))
print("12. 25th Percentile:", np.percentile(arr, 25))
print("13. 50th Percentile (Median):", np.percentile(arr, 50))
print("14. 75th Percentile:", np.percentile(arr, 75))
print(np.sort(arr))

Original Array: [10 20 30 40 50]
1. Sum: 150
2. Mean (Average): 30.0
3. Median: 30.0
4. Standard Deviation: 14.142135623730951
5. Variance: 200.0
6. Minimum Value: 10
7. Maximum Value: 50
8. Index of Minimum Value: 0
9. Index of Maximum Value: 4
10. Cumulative Sum: [ 10  30  60 100 150]
11. Cumulative Product: [      10      200     6000   240000 12000000]
12. 25th Percentile: 20.0
13. 50th Percentile (Median): 30.0
14. 75th Percentile: 40.0
[10 20 30 40 50]


In [66]:
  #vectorize -> convert a regular function to be applied on an array.

import numpy as np
def square(x):
    return x*x
vfunc=np.vectorize(square)

arr=np.array([1,2,3,4])
print(vfunc(arr))

[ 1  4  9 16]


In [67]:
#Broadcasting -> Numpy compares the shape of the arrays from the end (right to left) & follows these rules
   #*If shapes are equal they're compatible
   #*If one is 1,it can be started to match the other.
   #*If shapes are different & not 1 or equal -> error.

import numpy as np


arr = np.array([1, 2, 3, 4])
print(arr + 5)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

print(matrix + vector)


[6 7 8 9]
[[11 22 33]
 [14 25 36]]


In [68]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
mask = np.logical_and(arr > 15, arr < 35)
print(mask)



[False  True  True False False]


In [69]:
#The main difference between a copy and a view of an array is that the copy is a new array,
# and the view is just a view of the original array

#view

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [70]:
#copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


#NUMPY's STRUCTURED ARRAY

*Structured Array is similar to the Struct in c.It is used for grouping data of different data types and sizes.

*structured arra uses data containers called fields.Each data field can contain data of any data type and size.

*Array elements can be accessed with the help of dot notation.

*To create a structured array in Numpy,we need to define a dtype(data type) that specifies the namesand types of each field.

In [71]:
import numpy as np

import numpy as np

# Define the structure (field names and data types)
employee_dtype = np.dtype([
    ('name', 'U10'),     # 'U10' = string of max length 10
    ('age', 'i4'),       # 'i4' = 4-byte integer
    ('salary', 'f8')     # 'f8' = 8-byte float
])

# Create an array of structured data
employees = np.array([
    ('Alice', 25, 50000.0),
    ('Bob', 30, 60000.0),
    ('Charlie', 28, 55000.0)
], dtype=employee_dtype)

print(employees)

print(employees['name'])
# Output: ['Alice' 'Bob' 'Charlie']

print(employees['age'])
# Output: [25 30 28]

print(employees['salary'])
# Output: [50000. 60000. 55000.]



[('Alice', 25, 50000.) ('Bob', 30, 60000.) ('Charlie', 28, 55000.)]
['Alice' 'Bob' 'Charlie']
[25 30 28]
[50000. 60000. 55000.]


In [79]:
import numpy as np

# Define the structure (field names and data types)
dt = np.dtype([('name', 'U20'),('age', np.int32),('grade', np.float64)])

data = np.array([('Alice', 25, 4.8), ('Bob', 23, 3.9), ('Charlie', 27, 4.5)], dtype=dt)

a = np.array([('Sana', 2, 21.0),('Mansi', 7, 29.0)], dtype=dt)

         # Sorting according to the name
b = np.sort(a, order='name')
print('Sorting according to the name', b)

        # Sorting according to the age
b = np.sort(a, order='age')
print('\nSorting according to the age',b)

            # New record
new_record = np.array([('Anjali', 5, 24.5)], dtype=dt)
# Concatenate the new record to the existing array
a = np.concatenate((a, new_record))
print("After adding new record:\n", a)
# New dtype with an added column 'status'
new_dt = np.dtype([('name', 'U20'), ('age', np.int32), ('grade', np.float64), ('status', 'U10')])
# Create new structured array with default status 'Pass'
new_array = np.empty(a.shape, dtype=new_dt)
# Copy old data
new_array['name'] = a['name']
new_array['age'] = a['age']
new_array['grade'] = a['grade']
new_array['status'] = 'Pass'  # default value
print("After adding new column:\n", new_array)

Sorting according to the name [('Mansi', 7, 29.) ('Sana', 2, 21.)]

Sorting according to the age [('Sana', 2, 21.) ('Mansi', 7, 29.)]
After adding new record:
 [('Sana', 2, 21. ) ('Mansi', 7, 29. ) ('Anjali', 5, 24.5)]
After adding new column:
 [('Sana', 2, 21. , 'Pass') ('Mansi', 7, 29. , 'Pass')
 ('Anjali', 5, 24.5, 'Pass')]


In [72]:
#Getting some elements out of an existing array and creating a new array out of them is called filtering.
#In NumPy, you filter an array using a boolean index list


# Filter employees with salary > 55000
high_salary = employees[employees['salary'] > 55000]
print(high_salary)

employees['salary'] *= 1.10  # Give 10% raise
print(employees)

# Sort by salary
sorted_employees = np.sort(employees, order='salary')
print(sorted_employees)


[('Bob', 30, 60000.)]
[('Alice', 25, 55000.) ('Bob', 30, 66000.) ('Charlie', 28, 60500.)]
[('Alice', 25, 55000.) ('Charlie', 28, 60500.) ('Bob', 30, 66000.)]


In [73]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)



arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
[False False  True  True]
[43 44]
