Q2. (a). Answer the following questions using NumPy built-in functions.

(i). Write a python command to create a 4×2 array "a" using elements 10 to 17.

(ii) Write a python command to reshape the above array "a" to another array "a_reshape" of size 2x4 and write the output.

(iii) Write a python command to transpose the array "a" to another array "a_transpose" and write the output.

(i) np.arange(1,11).reshape(2,5)

(ii) np.hsplit(y,[4])

(iii) np.hsplit(y,[1,4])

(iv) np.vsplit(y,[2])

(v) np.split(y, [2], axis=1)

In [37]:
import numpy as np

arr=np.array([[10,11],[12,13],[14,15],[16,17]])
print(arr)
print(arr.shape)


a = np.arange(10, 18).reshape(4, 2)
print(a)

[[10 11]
 [12 13]
 [14 15]
 [16 17]]
(4, 2)
[[10 11]
 [12 13]
 [14 15]
 [16 17]]


In [38]:
a_reshape=arr.reshape(2,4)
print(a_reshape)


[[10 11 12 13]
 [14 15 16 17]]


In [39]:
a_transpose=arr.transpose()
print(a_transpose)

[[10 12 14 16]
 [11 13 15 17]]


In [40]:
import numpy as np

y = np.arange(1, 11).reshape(2, 5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
np.hsplit(y, [4])          #Split by columns before col 4

[array([[1, 2, 3, 4],
        [6, 7, 8, 9]]),
 array([[ 5],
        [10]])]

In [42]:
np.hsplit(y,[1,4])     #Split by columns before col 1 and 4


[array([[1],
        [6]]),
 array([[2, 3, 4],
        [7, 8, 9]]),
 array([[ 5],
        [10]])]

In [43]:
np.vsplit(y,[2])       #Split by rows before row 2

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([], shape=(0, 5), dtype=int64)]

In [44]:
np.split(y, [2], axis=1)    #Split by columns before col 2

[array([[1, 2],
        [6, 7]]),
 array([[ 3,  4,  5],
        [ 8,  9, 10]])]

In [45]:
import pandas as pd

# DataFrame 1
df1 = pd.DataFrame({
    'A': [7, 95, 66],
    'B': [3, 21, 8],
    'C': [80, 6, 0],
    'D': [45, 1, 23]
}, index=[1, 2, 3])

# DataFrame 2
df2 = pd.DataFrame({
    'A': [7, 95, 66],
    'B': [3, 21, 8],
    'D': [80, 6, 0],
    'E': [45, 1, 23]
}, index=[1, 2, 3])

print("df1:\n", df1)
print("\ndf2:\n", df2)


df1:
     A   B   C   D
1   7   3  80  45
2  95  21   6   1
3  66   8   0  23

df2:
     A   B   D   E
1   7   3  80  45
2  95  21   6   1
3  66   8   0  23


In [46]:
df1+df2


A   B   C    D   E
1   14   6 NaN  125 NaN
2  190  42 NaN    7 NaN
3  132  16 NaN   23 NaN

In [47]:
pd.concat([df1, df2])

A   B     C   D     E
1   7   3  80.0  45   NaN
2  95  21   6.0   1   NaN
3  66   8   0.0  23   NaN
1   7   3   NaN  80  45.0
2  95  21   NaN   6   1.0
3  66   8   NaN   0  23.0

In [48]:
#.iloc[2] means: 3rd row (index position 2)

df1.iloc[2]

A    66
B     8
C     0
D    23
Name: 3, dtype: int64

In [49]:
#df1.iloc[1] is the second row: [A=95, B=21, C=6, D=1]

df1 - df1.iloc[1]

A   B   C   D
1 -88 -18  74  44
2   0   0   0   0
3 -29 -13  -6  22

Q3. (a). Suppose there are 30 students in your class and their weights vary in the range of 45 to 60 kg (both inclusive). Write a python command to create a Pandas series containing the weights of the students and write the output.


create a data frame:
(i) Write a python command to fill all the missing values using forward filling across columns. (ii) Write a python command to drop the columns containing all missing values. (iii) Write a python command to print all the rows containing at least 2 non-missing values. (iv) Write a python command to drop the rows containing all missing values.


In [50]:
import pandas as pd

weights=pd.Series(np.random.randint(45,61,30))
print(weights)


0     54
1     60
2     60
3     52
4     46
5     58
6     48
7     50
8     60
9     59
10    48
11    58
12    60
13    48
14    51
15    55
16    52
17    50
18    52
19    50
20    54
21    48
22    54
23    48
24    51
25    58
26    54
27    60
28    46
29    48
dtype: int64


In [51]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    0: [1.0, 2.0, np.nan, np.nan, np.nan],
    1: [np.nan, 3.0, 4.0, 8.0, np.nan],
    2: [2.0, 5.0, 6.0, np.nan, np.nan],
    3: [np.nan, np.nan, np.nan, np.nan, np.nan]
})
print(df)


     0    1    2   3
0  1.0  NaN  2.0 NaN
1  2.0  3.0  5.0 NaN
2  NaN  4.0  6.0 NaN
3  NaN  8.0  NaN NaN
4  NaN  NaN  NaN NaN


In [52]:
df_fill=df.ffill(axis=1)   #Forward fill across columns means fill NaN horizontally (left to right)
print(df_fill)

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0
3  NaN  8.0  8.0  8.0
4  NaN  NaN  NaN  NaN


In [53]:
df.dropna(axis=1, how='all', inplace=True)
print(df)

     0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0
3  NaN  8.0  NaN
4  NaN  NaN  NaN


In [54]:
df.dropna(axis=0,how='all',inplace=True)
print(df)

     0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0
3  NaN  8.0  NaN


In [55]:
print(df[df.count(axis=1)>=2])

     0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0


Q2. Create an array using numpy and perform the following operations and illustrate appropriate output for each command.

i) arr-np.arange(2, 27) (2M)

ii) arr[1], arr[-1] ((2M))

iii)shape=arr.reshape(5,5) (2M)

iv) arr[0,0], arr[0,-2] (3M)

v) print("The size of 2D array size is:", arr.size) (2M)

arr.size (1M) vi)

vii) arr.ndim (1M)

viii) Display the size of array elements and total size of the array (2M)

In [61]:
import numpy as np

arr=np.arange(2,27)
print(arr)
print(arr.size)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26]
25


In [60]:
arr_reshape=arr.reshape(5,5)
arr_reshape

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [64]:
print(arr.ndim)
print(arr.size)
print(arr.itemsize)    #ach element (integer) uses 8 bytes
print(arr.nbytes)        #This gives the total number of bytes used by the entire array.

1
25
8
200



1️⃣ colour.str.capitalize() → Capitalizes the first letter of each string.

2️⃣ colour.str.split() → Splits each string into a list of words (based on spaces).

3️⃣ colour.str.startswith('y') → Checks if each string starts with the letter 'y'.

4️⃣ colour.str[3:5] → Extracts characters from index 3 to 4 of each string.

5️⃣ colour.str.strip() → Removes leading and trailing spaces from each string.

6️⃣ colour.index = [...] → Assigns a new (random/custom) index to the Series.